### ISSUE TITLE
Scripts directory as NPM module?

### ISSUE THREAD

**Issue by ttrider** [jaime-olivares/vscode-yuml#16]
Hello Jaime,

I absolutely love your project - I moved my team to use it for diagramming from Visio and Balsamiq (we still use Balsamiq for mockups).

We wrote a set of internal tools that expose some information into your flavor of yUml and then we load them into VSCode, generate .svg for the documentation and close VSCode.

It would be amazing if you can expose your .svg generation code as an NPM module, so we can integrate this process with our tools.

I would love to help you!

Thank You,

Vladimir

**Comment by jaime-olivares** [comment]
Hi Vladimir, already considered that possibility, it is just a matter of time.

**Comment by ttrider** [comment]
Do you need help on this? I’ll be happy to do it for you!

**Comment by aduh95** [comment]
Hey guys!

Is there any news on this? My team works with Plantuml to generate diagrams (node-plantuml FTW) but I would love to make them move to yUML in order to get rid of Java and Graphviz dependencies, which make the installation process way to heavy.

To make that possible, I'd need a NPM module which can convert within a node app yUML to SVG. I have already [forked this repo](https://github.com/aduh95/vscode-yuml) and started to work on the refactoring of the scripts directory to make it an NPM module. I can publish it if you want to.

**Comment by aduh95** [comment]
I published it on npm: [yuml2svg](https://www.npmjs.com/package/yuml2svg).

**Comment by jaime-olivares** [comment]
Already working on this. Have a look at: https://github.com/jaime-olivares/yuml

**Comment by jaime-olivares** [comment]
It is complete now. NPM package: https://www.npmjs.com/package/yuml-diagram
